// Public, fictional examples. Runtime-only operations use explicit review/receipt simulations.
const FEATURES = [
  [
    "codex",
    "Assistants",
    "Codex workspace",
    "chat",
    "Continue a project, choose Work or Plan, attach files and inspect a scripted task result.",
  ],
  [
    "gpt",
    "Assistants",
    "ChatGPT workspace",
    "chat",
    "Explore a separate conversation and keep its files and public progress summaries together.",
  ],
  [
    "history",
    "Assistants",
    "History & pins",
    "history",
    "Switch conversations, pin a chat and search the fictional history.",
  ],
  [
    "schedules",
    "Assistants",
    "Scheduled tasks",
    "schedule",
    "Prepare a chat-bound schedule and review its next example run.",
  ],
  [
    "dictation",
    "Assistants",
    "Dictation & speech",
    "microphone",
    "Explore voice input and reading controls without requesting microphone access.",
  ],
  [
    "profiles",
    "Assistants",
    "Behavior profiles",
    "person",
    "Choose project-specific working instructions and review their scope.",
  ],
  [
    "rotation",
    "Assistants",
    "Current chat & handoff",
    "arrow-right",
    "Review the project summary carried into the next conversation.",
  ],
  [
    "files",
    "Files & results",
    "Project files",
    "folder",
    "Browse folders, search, create, rename, upload, edit and download demo text files.",
  ],
  [
    "viewer",
    "Files & results",
    "Shared viewer & editor",
    "file",
    "Switch between reading and editing in the same window. Save a local demo copy.",
  ],
  [
    "formats",
    "Files & results",
    "Document & technical formats",
    "grid",
    "Explore the supported format families and clearly labeled sample previews.",
  ],
  [
    "images",
    "Files & results",
    "Images & annotations",
    "image",
    "Step through a gallery, draw on an image and export your annotated copy.",
  ],
  [
    "tables",
    "Files & results",
    "CSV & spreadsheet values",
    "table-header",
    "Edit a small table and export its values as CSV.",
  ],
  [
    "results",
    "Files & results",
    "Results feed",
    "bookmark",
    "Browse files, images, links and public task summaries beside the conversation.",
  ],
  [
    "batch",
    "Files & results",
    "Selection & export",
    "select",
    "Choose demo result files and export them together in a readable bundle.",
  ],
  [
    "sharing",
    "Files & results",
    "Share a result",
    "link",
    "Choose exact demo material and review its recipients before sharing.",
  ],
  [
    "git",
    "Git & delivery",
    "Working copy & diff",
    "branch",
    "Review changes, stage files, create a demo commit and inspect history.",
  ],
  [
    "issues",
    "Git & delivery",
    "Issues & pull requests",
    "repository",
    "Create an example issue, review a PR and see the resulting activity.",
  ],
  [
    "delivery",
    "Git & delivery",
    "Project delivery",
    "upload",
    "Review a branch, commit and pull-request delivery before simulating publication.",
  ],
  [
    "intake",
    "Git & delivery",
    "Engineering intake",
    "download",
    "Turn an example GitHub discussion into reviewed implementation work.",
  ],
  [
    "issue-drawer",
    "Git & delivery",
    "Issue drawer",
    "file-plus",
    "Prepare a finding, inspect its context and review the outgoing issue.",
  ],
  [
    "activity",
    "Git & delivery",
    "Space activity",
    "bell",
    "Read example commits, reviews and assignments in one project feed.",
  ],
  [
    "core",
    "Project organization",
    "Project Core",
    "folder",
    "Keep project purpose, rules and useful context in one editable document.",
  ],
  [
    "notes",
    "Project organization",
    "Notes",
    "note-edit",
    "Write a note, keep its draft and return to the conversation.",
  ],
  [
    "tasks",
    "Project organization",
    "Tasks",
    "check",
    "Create tasks, change their status and keep a launch checklist.",
  ],
  [
    "plans",
    "Project organization",
    "Plans & work review",
    "select",
    "Edit the plan, review a simulated execution and accept or request changes.",
  ],
  [
    "reports",
    "Project organization",
    "Reports",
    "file",
    "Read a project digest and generate a new example report.",
  ],
  [
    "capture",
    "Project organization",
    "Quick capture",
    "file-plus",
    "Capture a thought and choose whether it becomes a note, task or discussion.",
  ],
  [
    "prepare",
    "Project organization",
    "Prepare for Codex",
    "code",
    "Review a GPT discussion as a scoped implementation request.",
  ],
  [
    "search",
    "Project organization",
    "Search & commands",
    "search",
    "Find demo files, projects, conversations and any feature in this edition.",
  ],
  [
    "projects",
    "Project organization",
    "Projects & checkouts",
    "folder-plus",
    "Create a fictional project with a device and working-copy location.",
  ],
  [
    "spaces",
    "Collaboration",
    "Shared spaces",
    "people",
    "Explore members, roles, projects and shared material.",
  ],
  [
    "communication",
    "Collaboration",
    "Messages & discussions",
    "chat",
    "Post locally in an example team discussion.",
  ],
  [
    "brainstorm",
    "Collaboration",
    "Brainstorm rooms",
    "people",
    "Collect ideas, vote and turn a selected idea into a project note.",
  ],
  [
    "links",
    "Collaboration",
    "Project links & consultations",
    "link",
    "Review a bounded exchange between two example projects.",
  ],
  [
    "bridge",
    "Collaboration",
    "Bridge coordination",
    "link",
    "Inspect the coordinator, linked project scopes and example decisions.",
  ],
  [
    "sync",
    "Collaboration",
    "Checkout synchronization",
    "refresh",
    "Review an incoming revision for a participant's independent working copy.",
  ],
  [
    "notifications",
    "Collaboration",
    "Notifications",
    "bell",
    "Separate workspace activity from GPT answers and mark examples read.",
  ],
  [
    "devices",
    "Devices",
    "System & terminal",
    "terminal",
    "Switch machines and terminal sessions; try help, ls, pwd or a demo build.",
  ],
  [
    "remote",
    "Devices",
    "Remote Desktop",
    "monitor",
    "Open example desktop apps and try the text-paste handoff.",
  ],
  [
    "browser",
    "Devices",
    "Companion browser",
    "external",
    "Explore an isolated example browser session and its page controls.",
  ],
  [
    "gui",
    "Devices",
    "Application previews",
    "monitor",
    "Choose a configured app and open its example preview.",
  ],
  [
    "computer-use",
    "Devices",
    "Computer Use",
    "touch",
    "Review an example task, its selected window and simulated action receipt.",
  ],
  [
    "companion",
    "Devices",
    "Companion & onboarding",
    "server",
    "Walk through a device setup checklist with simulated component checks.",
  ],
  [
    "linux",
    "Devices",
    "Personal Linux",
    "server",
    "See the independent Linux/SSH direction and its current readiness boundary.",
  ],
  [
    "settings",
    "Settings & account",
    "Appearance & layout",
    "settings",
    "Change the real demo theme, panels and text size; reset your demo workspace.",
  ],
  [
    "connections",
    "Settings & account",
    "Connections",
    "link",
    "Inspect example Codex, GPT and GitHub bindings for each machine.",
  ],
  [
    "usage",
    "Settings & account",
    "Limits & credits",
    "schedule",
    "Inspect fictional usage and reset information for the selected machine.",
  ],
  [
    "data",
    "Settings & account",
    "History, storage & backups",
    "archive",
    "Review the example retention policy and simulate a backup receipt.",
  ],
  [
    "updates",
    "Settings & account",
    "Updates & diagnostics",
    "refresh",
    "Review a staged example update without touching an installation.",
  ],
  [
    "doctor",
    "Settings & account",
    "Bridge Doctor",
    "check",
    "Inspect a simulated compatibility incident in its independent conversation.",
  ],
  [
    "account",
    "Settings & account",
    "My account",
    "person",
    "Edit the demo display name and inspect account/session settings.",
  ],
  [
    "users",
    "Settings & account",
    "Users & access",
    "people",
    "Invite an example member and explore scoped roles.",
  ],
  [
    "help",
    "Settings & account",
    "User guide",
    "help",
    "Find an explanation and open the corresponding interactive example.",
  ],
  [
    "windows",
    "Workspace",
    "Windows, dock & panels",
    "grid",
    "Drag and resize windows, minimize them to the dock and resize the side panels.",
  ],
];
const FLOWS = {
  schedules: {
    title: "Scheduled task",
    intro: "A schedule belongs to one conversation. This example will not run in the background.",
    fields: [
      ["Task", "Summarize open review comments"],
      ["Conversation", "Northstar / Release preparation"],
      ["Schedule", "Every weekday at 09:00"],
    ],
    result:
      "Demo schedule saved. Next example run: tomorrow at 09:00. No timer or native job was started.",
  },
  profiles: {
    title: "Project behavior",
    intro: "Instructions remain scoped to the selected project.",
    fields: [
      ["Profile", "Careful implementation"],
      [
        "Instructions",
        "Keep changes focused. Preserve the existing visual language. Report checks and remaining work.",
        "textarea",
      ],
    ],
    result: "The fictional Northstar profile has been updated.",
  },
  rotation: {
    title: "Conversation handoff",
    intro: "Review what the next conversation receives. Previous conversations stay available.",
    fields: [
      ["Next title", "Northstar · Release follow-up"],
      [
        "Context",
        "Gallery is ready. Mobile layout was reviewed. Next: prepare release notes. Preserve the public API.",
        "textarea",
      ],
    ],
    result: "Example handoff prepared; the existing conversation and files remain intact.",
  },
  sharing: {
    title: "Share selected material",
    intro:
      "Review the exact material and people before sharing. Demo changes stay in this browser.",
    fields: [
      ["Material", "Release notes.md"],
      ["Recipient", "Jamie Chen"],
      ["Access", "Viewer"],
    ],
    result: "Release notes.md is now marked as shared with Jamie in this example.",
  },
  delivery: {
    title: "Deliver project work",
    intro: "Commit, branch and pull request are reviewed as one explicit delivery.",
    fields: [
      ["Branch", "demo/gallery-release"],
      ["Commit message", "Prepare the responsive gallery"],
      ["Pull request", "Gallery: responsive layout and keyboard navigation"],
    ],
    result:
      "Demo delivery recorded: branch prepared, commit saved, pull request #24 ready for review. Nothing was sent to GitHub.",
  },
  intake: {
    title: "Prepare incoming feedback",
    intro: "A discussion becomes an implementation request only after reviewing its scope.",
    fields: [
      ["Source", "Issue #18 · Gallery keyboard navigation"],
      ["Request", "Keep the selected image in view and support arrow-key navigation.", "textarea"],
    ],
    result: "Demo intake prepared for Northstar. Open Codex to continue the scripted example.",
  },
  "issue-drawer": {
    title: "Publish a finding",
    intro: "Review the selected context before creating an issue.",
    fields: [
      ["Repository", "demo/northstar"],
      ["Title", "Improve empty gallery feedback"],
      [
        "Description",
        "When no images match a filter, show a clear message and a reset action.",
        "textarea",
      ],
    ],
    result: "Example issue #25 added to the local review queue. No external publication occurred.",
  },
  prepare: {
    title: "Prepare for Codex",
    intro: "Keep research and implementation separate, with an explicit handoff.",
    fields: [
      ["Project", "Northstar"],
      [
        "Scope",
        "Implement the reviewed gallery. Keep existing URLs. Include phone and tablet layouts.",
        "textarea",
      ],
      [
        "Acceptance",
        "Navigation works with touch and keyboard; the selected image remains visible.",
        "textarea",
      ],
    ],
    result:
      "Implementation request prepared. It is ready to copy into the demo Codex conversation.",
  },
  links: {
    title: "Project consultation",
    intro: "Related projects exchange a bounded question while keeping their own workspaces.",
    fields: [
      ["From", "Northstar"],
      ["To", "Atlas"],
      ["Question", "Can we reuse the existing image metadata format?"],
      ["Round limit", "3", "number"],
    ],
    result:
      "Example consultation complete: Atlas recommends reusing the existing schema and adding an optional caption. No real project was contacted.",
  },
  bridge: {
    title: "Bridge coordination",
    intro:
      "A coordinator works with explicitly linked projects and keeps a trace of their decisions.",
    fields: [
      ["Coordinator", "Northstar"],
      ["Participants", "Atlas, Studio"],
      ["Objective", "Agree on a shared gallery metadata contract.", "textarea"],
    ],
    result:
      "Example decision saved: share the image metadata schema; keep each project's presentation independent.",
  },
  sync: {
    title: "Synchronize a checkout",
    intro: "Each participant keeps their own working copy. Review the revision before applying it.",
    fields: [
      ["Member", "Jamie Chen"],
      ["Checkout", "Studio PC / projects/northstar"],
      ["Incoming revision", "demo-1.2 · Responsive gallery"],
    ],
    result: "Example checkout synchronized. No local filesystem or repository was changed.",
  },
  "computer-use": {
    title: "Computer Use",
    intro:
      "The real integration operates in an authorized interactive session. This demo only illustrates the task and receipt.",
    fields: [
      ["Machine", "Studio PC"],
      ["Window", "Northstar preview"],
      ["Task", "Open the gallery and check its mobile navigation.", "textarea"],
    ],
    result:
      "Simulated action receipt: selected the preview window, opened the gallery, inspected navigation. No computer was controlled.",
  },
  data: {
    title: "History & backup",
    intro: "Backups and retention belong to the installation. The values below are fictional.",
    fields: [
      ["Scope", "Hub and workspace checkpoint"],
      ["Retention", "Latest 3 completed copies"],
      ["Schedule", "Daily when idle"],
    ],
    result:
      "Example checkpoint complete: metadata and working files verified; latest three demo checkpoints retained.",
  },
  updates: {
    title: "Update review",
    intro:
      "Real updates preserve active work and use the installation's maintenance admission. This is a local preview of the flow.",
    fields: [
      ["Component", "AbyssDeck web interface"],
      ["Version", "Demo release 1.2"],
      ["Changes", "Refined navigation and file previews; no data migration.", "textarea"],
    ],
    result:
      "Example update applied. The demo conversation and open-window drafts were preserved. No service was restarted.",
  },
  doctor: {
    title: "Bridge Doctor",
    intro:
      "An independent diagnostic conversation. Slow history alone is not a reason to repair or restart a client.",
    fields: [
      ["Incident", "Example native adapter compatibility change"],
      ["Message", "Inspect the adapter and preserve the current conversation.", "textarea"],
      ["Mode", "Diagnose"],
    ],
    result:
      "Example diagnosis: client is responsive, history is loading, no repair needed. No upstream probe was sent.",
  },
};
